version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=root123
      - DB_NAME=joyride_assessment
      - JWT_SECRET=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY3NDA1Njg5MCwiaWF0IjoxNjc0MDU2ODkwfQ.afx-wi0snsHmzBv-lL-0XGmT6YMX4_1orpN2WKNU0Bg
      - JWT_EXPIRATION=86400
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - GITHUB_TOKEN=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
    links:
      - db
      - redis
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: joyride_assessment
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    restart: always
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    volumes: 
      - redis:/data
volumes:
  db:
  redis: